### ISSUE TITLE
Pulsar 2.0 Documentation

### ISSUE THREAD

**Issue by sijie** [apache/incubator-pulsar#1446]
Created a master issue for tracking all the documentation tasks for pulsar 2.0.

- [ ] Documentation for Schema Registry #1457
- [ ] Documentation for Topic Compaction #1466
- [x] Documentation for Regex Subscription #1176 
- [x] Documentation for Builders
- [x] Documentation for Pulsar Functions (basic & java)
- [ ] Documentation for Pulsar Functions (python) #1482 
- [ ] Documentation for upgrading pulsar from 1.22.0 to 2.0
- [ ] Documentation for configuration store (renaming global zookeeper) 
- [x] Message deduplication #1271 
- [ ] Add "cookbooks" section with end-to-end instructions for specific tasks (like adding and removing nodes)
   - [x] Cookbook - Message Queue # 1507
- [ ] Cursors

**Comment by lucperkins** [comment]
- [ ] Message deduplication

**Comment by sijie** [comment]
@lucperkins added "message deduplication"

**Comment by sijie** [comment]
@lucperkins can you check the boxes what items are done?
